version: '3.8'

services:
  server:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  client_mobile:
    build:
      context: ./mobile
    depends_on:
      - server
    volumes:
      - shared:/shared

  client_web:
    build:
      context: ./frontend
    ports:
      - "8081:8081"
    depends_on:
      - server
      - client_mobile
    volumes:
      - shared:/shared
    networks:
      - app-network

volumes:
  shared:
    driver: local

networks:
  app-network:
    driver: bridge
