name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  footer: ^0.0.4
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  fluttertoast: ^8.2.8
  flutter_inappwebview: ^6.1.5
  loading_animation_widget: ^1.3.0
  flutter_phoenix: ^1.1.1
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/Google.webp
    - assets/icon/Github.webp
    - assets/icon/NoImage.webp
    - assets/icon/Spotify.webp
    - assets/icon/Gitlab.webp
    - assets/icon/Discord.webp
    - .env
