enum Steps {
    HOME,
    SELECT_SERVICE_ACTION,
    SELECT_ACTION,
    TRIGGER_ACTION,
    CONNECT_ACTION_SERVICE,
    SELECT_SERVICE_REACTION,
    SELECT_REACTION,
    TRIGGER_REACTION,
    CONNECT_REACTION_SERVICE,
    SUMMARY,
}

export default Steps