name: backend

on:
  pull_request:

jobs:
  check-compilation:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'backend')
    steps:
      - uses: actions/checkout@v4

      - name: Check backend compilation
        run: |
          cd backend
          go build main.go
           if [ $? -ne 0 ]; then
            echo "Compilation failed."
            exit 1
          else
            echo "Compilation succeed."
            exit 0
          fi

  check-unit-tests:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'backend')
    steps:
      - uses: actions/checkout@v4

      - name: Run backend unit tests
        run: |
          cd backend/src
          go test ./handler/*/ ./service/domain/*/ ./storage/postgres/*/
          if [ $? -ne 0 ]; then
            echo "Unit tests failed."
            exit 1
          else
            echo "Unit tests succeed."
            exit 0
          fi

  check-formatting:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'backend')
    steps:
      - uses: actions/checkout@v4

      - name: Run golang formatting on backend code
        run: |
          cd backend
          gofmt -w -s .

      - name: Push formatting changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git add backend
            git commit -m "style(back-end): :art: format code"
            git push -f origin "HEAD:${{ github.head_ref }}"
          fi
